// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
namespace message {
class command;
class commandDefaultTypeInternal;
extern commandDefaultTypeInternal _command_default_instance_;
class result;
class resultDefaultTypeInternal;
extern resultDefaultTypeInternal _result_default_instance_;
}  // namespace message
PROTOBUF_NAMESPACE_OPEN
template<> ::message::command* Arena::CreateMaybeMessage<::message::command>(Arena*);
template<> ::message::result* Arena::CreateMaybeMessage<::message::result>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace message {

// ===================================================================

class command PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:message.command) */ {
 public:
  inline command() : command(nullptr) {}
  virtual ~command();

  command(const command& from);
  command(command&& from) noexcept
    : command() {
    *this = ::std::move(from);
  }

  inline command& operator=(const command& from) {
    CopyFrom(from);
    return *this;
  }
  inline command& operator=(command&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const command& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const command* internal_default_instance() {
    return reinterpret_cast<const command*>(
               &_command_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(command& a, command& b) {
    a.Swap(&b);
  }
  inline void Swap(command* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(command* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline command* New() const final {
    return CreateMaybeMessage<command>(nullptr);
  }

  command* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<command>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const command& from);
  void MergeFrom(const command& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(command* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "message.command";
  }
  protected:
  explicit command(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEchoFieldNumber = 1,
    kDoingFun1FieldNumber = 2,
    kDoingFun2FieldNumber = 3,
  };
  // int32 echo = 1;
  void clear_echo();
  ::PROTOBUF_NAMESPACE_ID::int32 echo() const;
  void set_echo(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_echo() const;
  void _internal_set_echo(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 doing_fun1 = 2;
  void clear_doing_fun1();
  ::PROTOBUF_NAMESPACE_ID::int32 doing_fun1() const;
  void set_doing_fun1(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_doing_fun1() const;
  void _internal_set_doing_fun1(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 doing_fun2 = 3;
  void clear_doing_fun2();
  ::PROTOBUF_NAMESPACE_ID::int32 doing_fun2() const;
  void set_doing_fun2(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_doing_fun2() const;
  void _internal_set_doing_fun2(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:message.command)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 echo_;
  ::PROTOBUF_NAMESPACE_ID::int32 doing_fun1_;
  ::PROTOBUF_NAMESPACE_ID::int32 doing_fun2_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class result PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:message.result) */ {
 public:
  inline result() : result(nullptr) {}
  virtual ~result();

  result(const result& from);
  result(result&& from) noexcept
    : result() {
    *this = ::std::move(from);
  }

  inline result& operator=(const result& from) {
    CopyFrom(from);
    return *this;
  }
  inline result& operator=(result&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const result& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const result* internal_default_instance() {
    return reinterpret_cast<const result*>(
               &_result_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(result& a, result& b) {
    a.Swap(&b);
  }
  inline void Swap(result* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(result* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline result* New() const final {
    return CreateMaybeMessage<result>(nullptr);
  }

  result* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<result>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const result& from);
  void MergeFrom(const result& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(result* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "message.result";
  }
  protected:
  explicit result(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string error = 2;
  void clear_error();
  const std::string& error() const;
  void set_error(const std::string& value);
  void set_error(std::string&& value);
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  std::string* mutable_error();
  std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // int32 success = 1;
  void clear_success();
  ::PROTOBUF_NAMESPACE_ID::int32 success() const;
  void set_success(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_success() const;
  void _internal_set_success(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:message.result)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
  ::PROTOBUF_NAMESPACE_ID::int32 success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// command

// int32 echo = 1;
inline void command::clear_echo() {
  echo_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 command::_internal_echo() const {
  return echo_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 command::echo() const {
  // @@protoc_insertion_point(field_get:message.command.echo)
  return _internal_echo();
}
inline void command::_internal_set_echo(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  echo_ = value;
}
inline void command::set_echo(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_echo(value);
  // @@protoc_insertion_point(field_set:message.command.echo)
}

// int32 doing_fun1 = 2;
inline void command::clear_doing_fun1() {
  doing_fun1_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 command::_internal_doing_fun1() const {
  return doing_fun1_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 command::doing_fun1() const {
  // @@protoc_insertion_point(field_get:message.command.doing_fun1)
  return _internal_doing_fun1();
}
inline void command::_internal_set_doing_fun1(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  doing_fun1_ = value;
}
inline void command::set_doing_fun1(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_doing_fun1(value);
  // @@protoc_insertion_point(field_set:message.command.doing_fun1)
}

// int32 doing_fun2 = 3;
inline void command::clear_doing_fun2() {
  doing_fun2_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 command::_internal_doing_fun2() const {
  return doing_fun2_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 command::doing_fun2() const {
  // @@protoc_insertion_point(field_get:message.command.doing_fun2)
  return _internal_doing_fun2();
}
inline void command::_internal_set_doing_fun2(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  doing_fun2_ = value;
}
inline void command::set_doing_fun2(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_doing_fun2(value);
  // @@protoc_insertion_point(field_set:message.command.doing_fun2)
}

// -------------------------------------------------------------------

// result

// int32 success = 1;
inline void result::clear_success() {
  success_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 result::_internal_success() const {
  return success_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 result::success() const {
  // @@protoc_insertion_point(field_get:message.result.success)
  return _internal_success();
}
inline void result::_internal_set_success(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  success_ = value;
}
inline void result::set_success(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:message.result.success)
}

// string error = 2;
inline void result::clear_error() {
  error_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& result::error() const {
  // @@protoc_insertion_point(field_get:message.result.error)
  return _internal_error();
}
inline void result::set_error(const std::string& value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:message.result.error)
}
inline std::string* result::mutable_error() {
  // @@protoc_insertion_point(field_mutable:message.result.error)
  return _internal_mutable_error();
}
inline const std::string& result::_internal_error() const {
  return error_.Get();
}
inline void result::_internal_set_error(const std::string& value) {
  
  error_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void result::set_error(std::string&& value) {
  
  error_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:message.result.error)
}
inline void result::set_error(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:message.result.error)
}
inline void result::set_error(const char* value,
    size_t size) {
  
  error_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:message.result.error)
}
inline std::string* result::_internal_mutable_error() {
  
  return error_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* result::release_error() {
  // @@protoc_insertion_point(field_release:message.result.error)
  return error_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void result::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  error_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:message.result.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
