// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto

#include "message.pb.h"
#include "message.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace message {

static const char* Grpc_test_method_names[] = {
  "/message.Grpc_test/_donig_fuc",
  "/message.Grpc_test/_donig_echo",
};

std::unique_ptr< Grpc_test::Stub> Grpc_test::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Grpc_test::Stub> stub(new Grpc_test::Stub(channel));
  return stub;
}

Grpc_test::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod__donig_fuc_(Grpc_test_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod__donig_echo_(Grpc_test_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Grpc_test::Stub::_donig_fuc(::grpc::ClientContext* context, const ::message::command& request, ::message::result* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::command, ::message::result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod__donig_fuc_, context, request, response);
}

void Grpc_test::Stub::experimental_async::_donig_fuc(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::command, ::message::result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod__donig_fuc_, context, request, response, std::move(f));
}

void Grpc_test::Stub::experimental_async::_donig_fuc(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod__donig_fuc_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::result>* Grpc_test::Stub::PrepareAsync_donig_fucRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::result, ::message::command, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod__donig_fuc_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::result>* Grpc_test::Stub::Async_donig_fucRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsync_donig_fucRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Grpc_test::Stub::_donig_echo(::grpc::ClientContext* context, const ::message::command& request, ::message::result* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::command, ::message::result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod__donig_echo_, context, request, response);
}

void Grpc_test::Stub::experimental_async::_donig_echo(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::command, ::message::result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod__donig_echo_, context, request, response, std::move(f));
}

void Grpc_test::Stub::experimental_async::_donig_echo(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod__donig_echo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::result>* Grpc_test::Stub::PrepareAsync_donig_echoRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::result, ::message::command, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod__donig_echo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::result>* Grpc_test::Stub::Async_donig_echoRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsync_donig_echoRaw(context, request, cq);
  result->StartCall();
  return result;
}

Grpc_test::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Grpc_test_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Grpc_test::Service, ::message::command, ::message::result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Grpc_test::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::command* req,
             ::message::result* resp) {
               return service->_donig_fuc(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Grpc_test_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Grpc_test::Service, ::message::command, ::message::result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Grpc_test::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::command* req,
             ::message::result* resp) {
               return service->_donig_echo(ctx, req, resp);
             }, this)));
}

Grpc_test::Service::~Service() {
}

::grpc::Status Grpc_test::Service::_donig_fuc(::grpc::ServerContext* context, const ::message::command* request, ::message::result* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Grpc_test::Service::_donig_echo(::grpc::ServerContext* context, const ::message::command* request, ::message::result* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message

