// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto
#ifndef GRPC_message_2eproto__INCLUDED
#define GRPC_message_2eproto__INCLUDED

#include "message.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace message {

class Grpc_test final {
 public:
  static constexpr char const* service_full_name() {
    return "message.Grpc_test";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status _donig_fuc(::grpc::ClientContext* context, const ::message::command& request, ::message::result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::result>> Async_donig_fuc(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::result>>(Async_donig_fucRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::result>> PrepareAsync_donig_fuc(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::result>>(PrepareAsync_donig_fucRaw(context, request, cq));
    }
    virtual ::grpc::Status _donig_echo(::grpc::ClientContext* context, const ::message::command& request, ::message::result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::result>> Async_donig_echo(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::result>>(Async_donig_echoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::result>> PrepareAsync_donig_echo(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::result>>(PrepareAsync_donig_echoRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void _donig_fuc(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void _donig_fuc(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void _donig_fuc(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void _donig_echo(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void _donig_echo(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void _donig_echo(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message::result>* Async_donig_fucRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message::result>* PrepareAsync_donig_fucRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message::result>* Async_donig_echoRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message::result>* PrepareAsync_donig_echoRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status _donig_fuc(::grpc::ClientContext* context, const ::message::command& request, ::message::result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::result>> Async_donig_fuc(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::result>>(Async_donig_fucRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::result>> PrepareAsync_donig_fuc(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::result>>(PrepareAsync_donig_fucRaw(context, request, cq));
    }
    ::grpc::Status _donig_echo(::grpc::ClientContext* context, const ::message::command& request, ::message::result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::result>> Async_donig_echo(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::result>>(Async_donig_echoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::result>> PrepareAsync_donig_echo(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::result>>(PrepareAsync_donig_echoRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void _donig_fuc(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void _donig_fuc(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void _donig_fuc(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void _donig_echo(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void _donig_echo(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void _donig_echo(::grpc::ClientContext* context, const ::message::command* request, ::message::result* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::message::result>* Async_donig_fucRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::message::result>* PrepareAsync_donig_fucRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::message::result>* Async_donig_echoRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::message::result>* PrepareAsync_donig_echoRaw(::grpc::ClientContext* context, const ::message::command& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod__donig_fuc_;
    const ::grpc::internal::RpcMethod rpcmethod__donig_echo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status _donig_fuc(::grpc::ServerContext* context, const ::message::command* request, ::message::result* response);
    virtual ::grpc::Status _donig_echo(::grpc::ServerContext* context, const ::message::command* request, ::message::result* response);
  };
  template <class BaseClass>
  class WithAsyncMethod__donig_fuc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod__donig_fuc() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod__donig_fuc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _donig_fuc(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Request_donig_fuc(::grpc::ServerContext* context, ::message::command* request, ::grpc::ServerAsyncResponseWriter< ::message::result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod__donig_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod__donig_echo() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod__donig_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _donig_echo(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Request_donig_echo(::grpc::ServerContext* context, ::message::command* request, ::grpc::ServerAsyncResponseWriter< ::message::result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod__donig_fuc<WithAsyncMethod__donig_echo<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod__donig_fuc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod__donig_fuc() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::message::command, ::message::result>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::message::command* request, ::message::result* response) { return this->_donig_fuc(context, request, response); }));}
    void SetMessageAllocatorFor__donig_fuc(
        ::grpc::experimental::MessageAllocator< ::message::command, ::message::result>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::message::command, ::message::result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod__donig_fuc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _donig_fuc(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* _donig_fuc(
      ::grpc::CallbackServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* _donig_fuc(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod__donig_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod__donig_echo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::message::command, ::message::result>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::message::command* request, ::message::result* response) { return this->_donig_echo(context, request, response); }));}
    void SetMessageAllocatorFor__donig_echo(
        ::grpc::experimental::MessageAllocator< ::message::command, ::message::result>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::message::command, ::message::result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod__donig_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _donig_echo(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* _donig_echo(
      ::grpc::CallbackServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* _donig_echo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod__donig_fuc<ExperimentalWithCallbackMethod__donig_echo<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod__donig_fuc<ExperimentalWithCallbackMethod__donig_echo<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod__donig_fuc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod__donig_fuc() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod__donig_fuc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _donig_fuc(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod__donig_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod__donig_echo() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod__donig_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _donig_echo(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod__donig_fuc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod__donig_fuc() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod__donig_fuc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _donig_fuc(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Request_donig_fuc(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod__donig_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod__donig_echo() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod__donig_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _donig_echo(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Request_donig_echo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod__donig_fuc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod__donig_fuc() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->_donig_fuc(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod__donig_fuc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _donig_fuc(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* _donig_fuc(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* _donig_fuc(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod__donig_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod__donig_echo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->_donig_echo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod__donig_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _donig_echo(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* _donig_echo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* _donig_echo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod__donig_fuc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod__donig_fuc() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::message::command, ::message::result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::message::command, ::message::result>* streamer) {
                       return this->Streamed_donig_fuc(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod__donig_fuc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status _donig_fuc(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamed_donig_fuc(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::message::command,::message::result>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod__donig_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod__donig_echo() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::message::command, ::message::result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::message::command, ::message::result>* streamer) {
                       return this->Streamed_donig_echo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod__donig_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status _donig_echo(::grpc::ServerContext* /*context*/, const ::message::command* /*request*/, ::message::result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamed_donig_echo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::message::command,::message::result>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod__donig_fuc<WithStreamedUnaryMethod__donig_echo<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod__donig_fuc<WithStreamedUnaryMethod__donig_echo<Service > > StreamedService;
};

}  // namespace message


#endif  // GRPC_message_2eproto__INCLUDED
